export enum NinTypeEnum {
  TYPE_REGULAR_NIN = 'TYPE_REGULAR_NIN',
  TYPE_D_NUMBER = 'TYPE_D_NUMBER',
  TYPE_H_NUMBER = 'TYPE_H_NUMBER',
  TYPE_NPR_SYNTHETIC = 'TYPE_NPR_SYNTHETIC'
}

export const ALL_NIN_TYPES = [
  NinTypeEnum.TYPE_REGULAR_NIN,
  NinTypeEnum.TYPE_D_NUMBER,
  NinTypeEnum.TYPE_H_NUMBER,
  NinTypeEnum.TYPE_NPR_SYNTHETIC
];
